language: node_js
node_js:
- '10'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
script:
- npm run lint
- npm run build
- xvfb-run npm run test:ci
- xvfb-run npm run e2e
deploy:
  provider: firebase
  token:
    secure: BZt0NdANt+ppLfAPghOLxcdoehN89KUJ56GZrRTdUZ1aW0M1HCzSIZw19seiACLwp/RyntoQ4rGd3NCRIBdn2xHhiOJz1GHrdVHj6NlkLWru45YisJtduWLByD1/SL7Irv1dHi8ngNHi9ZGUeftdKjGrV7JqVYi2XWiAcI0WSj16aAudNQ3tRJoh937KD6gTH83x5qkp7XKvlPbUiEdp0MGyuaNrN1oXN8SoWHLDs1FbumXT3ntCHScCQ/oADvJF3x0x8VC/0mzBIwIpETfVmZ6/ouP1u1WblAkmhjrpVGbZX2XLb34wFA/IhLUGEn6kELvcK+1gIfcqEzKQmgPYzXcUOb2EEGVZO4Irvst3AymbF9GRTTZk5Fn+v5h6hVwd/mvFjBi2+Mg1ndvyN6VxSPFlBlncpPkiyx7JRlE4KN6mR4vMStOx1htBQUkPZvlfDXfL8/7RBbDFyj42MuSnbIgYzQtQpyozqjRz8TWsNBXjeqND14hTPzNi10xOntFOHbxMpWgnnOfjKyzY5UBLun1mTEMny6GlUANl2EU1veq9yUCJ6b8nblCr5tfxlPyUv+9rCUx4pkqcljBDrFzSQSFRymPS3GMlJqTeNgt0+HcT8NDl7T9d9vjD5nZ6oIgj7+43ZWrGQn6F2W7GFuM/nTn9pQCvrEI6g/7YKsya99k=
  project: parkie-1551564963641
  skip_cleanup: true
  edge: true