language: node_js
node_js:
- '10'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
script:
- npm run lint
- npm run build
- xvfb-run npm run test:ci
- xvfb-run npm run e2e
deploy:
  provider: firebase
  token:
    secure: QvbXc9kJ1iNwtIvaFJEb2rNwVM0wEWsGNP3BEi68zdQY5doN5J5Ao2avB0tgLSvIKGnVgfJ6pL58ntioe69nar3ybZmmCogcLO+wpW3Itb0nCAH4R215SGtUHqgkBmgak+91GajtiJlGDtyMisVXc8byh8tMHi05WS+539bJkpXWZKkUj3vYl+rZemPxw7zIFDT6jw4sITc1n7Mh7fsz/KH5btyhWD2Pj1Vd92kQ2AZJb/1rzQhKz5jHpPL9WS64XLP+1UaPOUwnkzIYErEiOfiJtwhmFC2uA2q5MyO2qKTgUCgsWYXHxE3iyQkLFN1nxL89VmypPZXzve41FCyn/4BI3ST3bcrPmME7/oQytgPfPktsgkY6+xFK/izNEGLwdfXZHgXcqK8px5DvFG1dbl62yttojsTZAYgOKsgJKLefI/wQwwxdcVnnGJhQif/8DbGELx72xWp7aj9FKlcNio8q1JJpqlnyGqFuC8Dk4ZCnAdlNJ7ZaK3vIQbGs/H/WQoPE6qB/nCdJpCcqyAHxrC4cqkkymz1JI9YnAV/wh9QdtAdB+2dikjiqBcpwarNkqg9QS7oH6lWQBeBRdd9m5ZyI1e+cfn6Qj4Csy+Psi9xhQ/Ddxp7GXaxqIFkPXgh3TVQTXuiVpRTBsZSKcPF0eQmeTJYtG/7sIDTGBkvLH9U=
  project: parkie-1551564963641
  skip_cleanup: true