language: node_js
node_js:
- '10'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
script:
- npm run lint
- npm run build
- xvfb-run npm run test:ci
- xvfb-run npm run e2e
deploy:
  provider: firebase
  token:
    secure: BwPpZV0d7zAZdbsuxd8xSbpHnEbFcAlK8i1E+AlEdwlNtK0Mw9s8L8QpArTXOy+gFE0AQwPr8gYHoedqQ4uMyQsCjBPM2RQI1M0ojcIKduhdtdWCAgoeyTFzLG4y4p7nA4DXXNG7dCOJ3EjlUArIR74ibH3OiY1v+3m/n3S8YjlhfMmJIpd9XWEon1n06Sh8Jrk1NW3IbyKpefrqSi9zOZMMFZmSl/p8/JOsbvHRQG8s/5MClS1xLCgxA3sb2zCfy4RzseSdy3BGkgY0ReTjfb4YssH13lm/sluuGYEy62nOC+yndx2TS2GGIlXLFy6n+luJEh1KKyvNwIfNPjfowm19wd1FRvDLRchFZPI7UZBvHRHs1xk32eWyZ3KVr3kTKM+VNOc6t7JDElpyiJtcOmdXZXtJql2SAS8cjouEIsGqoaEslk87cjxbWVbHDSs4MawsYd3Rk4wkX4YkuU5A/TjNOJ2vZQtYNBPCL+7W1+fNptiI9GeTnvvOmZgSlBJDDQfF3jOENyzh/f6HyJwUNoo3G9Uolw8xy3Cz/DG9indT3lQefauwNbvEngKCu7v4Ke0K34h64/qP4BjpintAgxeX7gYF/iuZoLJiW2F4vDl6dECfwothXvsJxjsYV/HQEBnlqaEHGSee8aGPvy582lpBHZeaO9KhkeWXNtiJljE=
  project: parkie-1551564963641
  skip_cleanup: true
  edge: true