language: node_js
node_js:
- '10'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
script:
- npm run lint
- npm run build
- xvfb-run npm run test:ci
- xvfb-run npm run e2e
deploy:
  provider: firebase
  token:
    secure: cq22HD+xErV6m9G4pvZNKiyrCgG3BxM4CZiMKeNvM9XvdmtVUxSvOlAXrPv9lWCUFG7JiaTxclcjBG2k3iyNPOf4EA/EXhSv5A5qlp2PxxZiMOm6qoG/Z2Sg1iYsDI9V8eSdUdAh1zhlk+pX2uRwFpxQFN0NtzT089iQbW2XYI2pgWCzrwAHXZv4JiN5X1dK9gSoIJejcZR1VtOIsKjO5LEsBeQpHMpk49pogHrIyuclGk/a1tVqddD6P+pwDeOnc3lCe/8nUv+VWAhrobFD/jmvjkeh3Bk+L5l407sYSnQTemr2jM8HKmLzfJPQ8c2OB3jVRz3jVRX6j7fRAkVvyc+xfPt9yfno5I5u8OZ3Qmgem6VIFr9xM7KPcthI5QIcjjIb4jz6wnUFkyxynBXlut4eA8JuiybYRkBDXHvCpOfE0OJVf+kMC04hF+dYcd7E2KnHrWk+XeTr2xorgimK9+wJC2OCjJZPLf3behNYkEE4KMF8J7DSivZ3H7IxNTXZWw88T8z5penHP1ZeQsPxQX2ycDZG8keE9DR0IdTETLsrYlcnwpo2LWINhqnqXPOm26qvQ7w34r3JWXmYfpYBemoL8oHV8AtOkm1T1AF/+B6DTmF/tdJcoql1PcDuuE6yxKWUgwg/jkhB0u+5u79SnV7cxQIAc/Xws9NWauGGNSs=
  project: parkie-1551564963641
  skip_cleanup: true